"""
Data models for LLM Consultant Advisor.
All models use Pydantic v2 for validation and serialization.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Error codes
# ---------------------------------------------------------------------------


class ErrorCode(str, Enum):
    LLM_UNAVAILABLE = "LLM_001"
    LLM_TIMEOUT = "LLM_002"
    EXTRACTION_INSUFFICIENT = "ATTR_001"
    KB_EMPTY = "KB_001"
    KB_NO_RESULTS = "KB_002"
    CSV_INVALID_FORMAT = "CSV_001"
    CSV_MISSING_FIELDS = "CSV_002"
    EXPORT_FAILED = "EXP_001"
    EXTERNAL_API_ERROR = "EXT_001"
    EXTERNAL_API_TIMEOUT = "EXT_002"
    AUTH_EXPIRED = "AUTH_001"
    SESSION_EXPIRED = "AUTH_002"
    UNAUTHORIZED = "AUTH_003"


# ---------------------------------------------------------------------------
# Knowledge Base
# ---------------------------------------------------------------------------


class KnowledgeBaseSchema(BaseModel):
    required_fields: list[str]
    optional_fields: list[str]
    text_fields: list[str]  # fields used for embedding generation
    id_field: str


# ---------------------------------------------------------------------------
# External API
# ---------------------------------------------------------------------------


class ExternalAPIConfig(BaseModel):
    endpoint_url: str
    auth_type: Literal["bearer", "api_key", "basic"]
    credentials: dict[str, Any]  # stored encrypted
    timeout_seconds: int = 30


# ---------------------------------------------------------------------------
# Core domain models
# ---------------------------------------------------------------------------


class QueryItem(BaseModel):
    id: str  # UUID
    session_id: str
    raw_description: str  # original consultant text
    extracted_attributes: dict[str, Any] = Field(default_factory=dict)
    confirmed: bool = False
    embedding: list[float] | None = None


class Record(BaseModel):
    id: str  # UUID
    source_row_hash: str  # SHA-256 of the original CSV row
    attributes: dict[str, Any]  # normalized CSV fields
    embedding: list[float]
    created_at: datetime
    updated_at: datetime


class AttributeContribution(BaseModel):
    attribute_name: str
    contribution_score: float
    justification: str  # generated by LLM


class SimilarityResult(BaseModel):
    record: Record
    similarity_score: float = Field(ge=0.0, le=1.0)
    attribute_contributions: list[AttributeContribution] = Field(default_factory=list)


class Recommendation(BaseModel):
    text: str
    supporting_record_id: str  # mandatory reference to a Record


class AnalysisReport(BaseModel):
    id: str  # UUID
    session_id: str
    generated_at: datetime
    summary: str
    patterns: list[str]
    differences: list[str]
    recommendations: list[Recommendation]
    explainability: list[SimilarityResult]
    knowledge_base_size: int
    confidence_note: str | None = None  # filled when KB is insufficient


class ChatMessage(BaseModel):
    id: str  # UUID
    session_id: str
    role: Literal["user", "assistant", "system"]
    content: str
    timestamp: datetime
    metadata: dict[str, Any] = Field(default_factory=dict)


class Session(BaseModel):
    id: str  # UUID
    consultant_id: str
    created_at: datetime
    last_activity_at: datetime
    status: Literal["active", "expired", "closed"] = "active"
    query_item: QueryItem | None = None
    selected_record_ids: list[str] = Field(default_factory=list)
    similarity_results: list[SimilarityResult] = Field(default_factory=list)
